In [1]:
from LorisNet import *
import tensorflow as tf

In [2]:
X = tf.random.uniform((3, 4, 2))

X

<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
array([[[0.68901026, 0.95707357],
        [0.77311003, 0.51773214],
        [0.19281828, 0.38130546],
        [0.34489274, 0.97888815]],

       [[0.5978012 , 0.42876053],
        [0.39102936, 0.12214935],
        [0.57109725, 0.932186  ],
        [0.95773804, 0.72559774]],

       [[0.17522418, 0.62026286],
        [0.04013002, 0.6292093 ],
        [0.957111  , 0.3401643 ],
        [0.01441944, 0.9280187 ]]], dtype=float32)>

In [3]:
l = LinearSeparators(activation=None)

In [4]:
l(X)

<tf.Tensor: shape=(3, 4, 1), dtype=float32, numpy=
array([[[-0.5280725 ],
        [-0.5375518 ],
        [-0.47585836],
        [ 0.7189028 ]],

       [[-0.09293267],
        [-0.23568794],
        [-1.2462571 ],
        [ 0.35896236]],

       [[-0.47702128],
        [-0.18396515],
        [-1.0773754 ],
        [ 0.7589693 ]]], dtype=float32)>

In [5]:
l.kernel

<tf.Variable 'linear_separators/separators_kernel:0' shape=(4, 2) dtype=float32, numpy=
array([[ 0.4967966 , -0.9094081 ],
       [-0.52180123, -0.25909543],
       [-0.8315661 , -0.8274658 ],
       [-0.24772143,  0.82168746]], dtype=float32)>

In [6]:
l.bias

<tf.Variable 'linear_separators/separators_bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>

In [7]:
0.68901026*0.4967966 + 0.95707357*-0.9094081

-0.5280725023208012