In [1]:
from LorisNet import *
import tensorflow as tf
import numpy as np

# Regression

In [2]:
X = np.random.uniform(size=(10000, 4))

X[:10]

array([[0.92818598, 0.39719184, 0.58672172, 0.40332659],
       [0.72831645, 0.47525277, 0.6519997 , 0.25759524],
       [0.36445905, 0.21009308, 0.23068524, 0.29613332],
       [0.0508783 , 0.28626403, 0.65677339, 0.76826409],
       [0.10201524, 0.33988277, 0.46077175, 0.35342814],
       [0.06965797, 0.35955768, 0.12428881, 0.2976652 ],
       [0.9516091 , 0.67700319, 0.80271804, 0.07681157],
       [0.97227597, 0.88581188, 0.88119087, 0.31818135],
       [0.56832949, 0.46704907, 0.31654519, 0.5412616 ],
       [0.18837773, 0.21605723, 0.43266278, 0.4509968 ]])

In [3]:
y = np.expand_dims((X[:, 0] > .3).astype(np.float32)*3+1, -1)

y[:10]

array([[4.],
       [4.],
       [4.],
       [1.],
       [1.],
       [1.],
       [4.],
       [4.],
       [4.],
       [1.]], dtype=float32)

In [4]:
data = tf.data.Dataset.from_tensor_slices((X, y)).batch(1000)
data

<BatchDataset element_spec=(TensorSpec(shape=(None, 4), dtype=tf.float64, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))>

In [5]:
model = tf.keras.Sequential()

number_masks = 2
steps = [StepNoFeedback(SigmoidMaskedInputNoFeedback(number_masks=number_masks),
                        LinearSeparators(),
                        PredictionNeurons(units=1)),
         StepWithFeedback(SigmoidMaskedInputWithFeedback(number_masks=number_masks),
                          LinearSeparators(),
                          PredictionNeurons(units=1))]
    
model.add(LorisNetLayer(steps=steps,
                        weighted_addition=WeightedAdd(),
                        activation='linear'
                       ))

model.compile(loss=tf.losses.MeanSquaredError(),
              optimizer=tf.keras.optimizers.Adam(learning_rate=.01),
              metrics=['mae'])

history = model.fit(data,
                    epochs=100,
                    verbose=1)

Epoch 1/100
10/10 [==============================] - 2s 5ms/step - loss: 7.2591 - mae: 2.3778
Epoch 2/100
10/10 [==============================] - 0s 5ms/step - loss: 4.1534 - mae: 1.7781
Epoch 3/100
10/10 [==============================] - 0s 6ms/step - loss: 2.0557 - mae: 1.3813
Epoch 4/100
10/10 [==============================] - 0s 6ms/step - loss: 1.2971 - mae: 1.0082
Epoch 5/100
10/10 [==============================] - 0s 5ms/step - loss: 1.1361 - mae: 0.8056
Epoch 6/100
10/10 [==============================] - 0s 5ms/step - loss: 0.9195 - mae: 0.7769
Epoch 7/100
10/10 [==============================] - 0s 5ms/step - loss: 0.7978 - mae: 0.7612
Epoch 8/100
10/10 [==============================] - 0s 5ms/step - loss: 0.7164 - mae: 0.6925
Epoch 9/100
10/10 [==============================] - 0s 4ms/step - loss: 0.6517 - mae: 0.6319
Epoch 10/100
10/10 [==============================] - 0s 6ms/step - loss: 0.6027 - mae: 0.6067
Epoch 11/100
10/10 [==============================] - 0s 6m

In [6]:
X_test = [[.9, .1, .1, .1], [.1, .1, .1, .1]]
model.predict(X_test)

1/1 [==============================] - 1s 604ms/step


array([[3.978256 ],
       [0.9716222]], dtype=float32)

In [7]:
y = np.expand_dims(X[:, 0]*2 - X[:, 1]**3 + X[:, 2]/3, -1)
y

array([[1.98928434],
       [1.56662308],
       [0.79653985],
       ...,
       [1.28733072],
       [1.88495031],
       [1.57916985]])

In [8]:
data = tf.data.Dataset.from_tensor_slices((X, y)).batch(1000)
data

<BatchDataset element_spec=(TensorSpec(shape=(None, 4), dtype=tf.float64, name=None), TensorSpec(shape=(None, 1), dtype=tf.float64, name=None))>

In [9]:
model = tf.keras.Sequential()

number_masks = 5
steps = [StepNoFeedback(AllOnesMaskedInputNoFeedback(number_masks=number_masks),
                        LinearSeparators(),
                        PredictionNeurons(units=1)),
         StepWithFeedback(AllOnesMaskedInputWithFeedback(number_masks=number_masks),
                          LinearSeparators(),
                          PredictionNeurons(units=1)),
        StepWithFeedback(AllOnesMaskedInputWithFeedback(number_masks=number_masks),
                          LinearSeparators(),
                          PredictionNeurons(units=1)),
        StepWithFeedback(AllOnesMaskedInputWithFeedback(number_masks=number_masks),
                          LinearSeparators(),
                          PredictionNeurons(units=1)),
        StepWithFeedback(AllOnesMaskedInputWithFeedback(number_masks=number_masks),
                          LinearSeparators(),
                          PredictionNeurons(units=1)),
        StepWithFeedback(AllOnesMaskedInputWithFeedback(number_masks=number_masks),
                          LinearSeparators(),
                          PredictionNeurons(units=1)),
        StepWithFeedback(AllOnesMaskedInputWithFeedback(number_masks=number_masks),
                          LinearSeparators(),
                          PredictionNeurons(units=1))]
    
model.add(LorisNetLayer(steps=steps,
                        weighted_addition=WeightedAdd(),
                        activation='linear'
                       ))

model.compile(loss=tf.losses.MeanSquaredError(),
              optimizer=tf.keras.optimizers.Adam(learning_rate=.01),
              metrics=['mae'])

history = model.fit(data,
                    epochs=100,
                    verbose=1)

Epoch 1/100
10/10 [==============================] - 5s 6ms/step - loss: 2.3206 - mae: 1.2639
Epoch 2/100
10/10 [==============================] - 0s 7ms/step - loss: 0.5622 - mae: 0.6102
Epoch 3/100
10/10 [==============================] - 0s 7ms/step - loss: 0.3133 - mae: 0.4466
Epoch 4/100
10/10 [==============================] - 0s 7ms/step - loss: 0.1597 - mae: 0.3469
Epoch 5/100
10/10 [==============================] - 0s 7ms/step - loss: 0.1137 - mae: 0.2568
Epoch 6/100
10/10 [==============================] - 0s 6ms/step - loss: 0.0995 - mae: 0.2509
Epoch 7/100
10/10 [==============================] - 0s 6ms/step - loss: 0.0945 - mae: 0.2536
Epoch 8/100
10/10 [==============================] - 0s 7ms/step - loss: 0.0891 - mae: 0.2361
Epoch 9/100
10/10 [==============================] - 0s 7ms/step - loss: 0.0861 - mae: 0.2429
Epoch 10/100
10/10 [==============================] - 0s 7ms/step - loss: 0.0830 - mae: 0.2329
Epoch 11/100
10/10 [==============================] - 0s 7m

In [10]:
model(X[:10])

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[1.9755255 ],
       [1.5708847 ],
       [0.79701453],
       [0.29564556],
       [0.28439435],
       [0.12408239],
       [1.8345274 ],
       [1.4964092 ],
       [1.1104985 ],
       [0.47234792]], dtype=float32)>

In [11]:
y[:10]

array([[1.98928434],
       [1.56662308],
       [0.79653985],
       [0.29722255],
       [0.31835771],
       [0.1342613 ],
       [1.86049776],
       [1.54321869],
       [1.14029437],
       [0.51089068]])

In [12]:
X_test = np.random.uniform(size=(5, 4))
y_test = np.expand_dims(X_test[:, 0]*2 - X_test[:, 1]**3 + X_test[:, 2]/3, -1)
y_test

array([[0.19795079],
       [1.4474371 ],
       [1.93163943],
       [1.76410579],
       [0.41098692]])

In [13]:
model(X_test)

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[0.16716534],
       [1.4492903 ],
       [1.9176673 ],
       [1.7557503 ],
       [0.41030315]], dtype=float32)>

In [14]:
model = tf.keras.Sequential()

number_masks = 5
masks_reg =.1
steps = [StepNoFeedback(SigmoidMaskedInputNoFeedback(number_masks=number_masks,
                                                     activity_regularizer=tf.keras.regularizers.L2(masks_reg)),
                        LinearSeparators(),
                        PredictionNeurons(units=1)),
         StepWithFeedback(SigmoidMaskedInputWithFeedback(number_masks=number_masks,
                                                         activity_regularizer=tf.keras.regularizers.L2(masks_reg)),
                          LinearSeparators(),
                          PredictionNeurons(units=1)),
         StepWithFeedback(SigmoidMaskedInputWithFeedback(number_masks=number_masks,
                                                         activity_regularizer=tf.keras.regularizers.L2(masks_reg)),
                          LinearSeparators(),
                          PredictionNeurons(units=1)),
         StepWithFeedback(SigmoidMaskedInputWithFeedback(number_masks=number_masks,
                                                         activity_regularizer=tf.keras.regularizers.L2(masks_reg)),
                          LinearSeparators(),
                          PredictionNeurons(units=1)),
         StepWithFeedback(SigmoidMaskedInputWithFeedback(number_masks=number_masks,
                                                         activity_regularizer=tf.keras.regularizers.L2(masks_reg)),
                          LinearSeparators(),
                          PredictionNeurons(units=1)),
         StepWithFeedback(SigmoidMaskedInputWithFeedback(number_masks=number_masks,
                                                         activity_regularizer=tf.keras.regularizers.L2(masks_reg)),
                          LinearSeparators(),
                          PredictionNeurons(units=1)),
         StepWithFeedback(SigmoidMaskedInputWithFeedback(number_masks=number_masks,
                                                         activity_regularizer=tf.keras.regularizers.L2(masks_reg)),
                          LinearSeparators(),
                          PredictionNeurons(units=1))]
    
model.add(LorisNetLayer(steps=steps,
                        weighted_addition=WeightedAdd(),
                        activation='linear'
                       ))

model.compile(loss=tf.losses.MeanSquaredError(),
              optimizer=tf.keras.optimizers.Adam(learning_rate=.01),
              metrics=['mae']
             )

history = model.fit(data,
                    epochs=100,
                    verbose=1)

Epoch 1/100
10/10 [==============================] - 6s 9ms/step - loss: 19.5379 - mae: 0.4161
Epoch 2/100
10/10 [==============================] - 0s 9ms/step - loss: 16.1321 - mae: 0.2440
Epoch 3/100
10/10 [==============================] - 0s 12ms/step - loss: 13.4230 - mae: 0.1915
Epoch 4/100
10/10 [==============================] - 0s 11ms/step - loss: 11.2395 - mae: 0.1527
Epoch 5/100
10/10 [==============================] - 0s 9ms/step - loss: 9.4902 - mae: 0.1349
Epoch 6/100
10/10 [==============================] - 0s 8ms/step - loss: 8.0850 - mae: 0.1293
Epoch 7/100
10/10 [==============================] - 0s 9ms/step - loss: 6.9484 - mae: 0.1275
Epoch 8/100
10/10 [==============================] - 0s 8ms/step - loss: 6.0216 - mae: 0.1261
Epoch 9/100
10/10 [==============================] - 0s 8ms/step - loss: 5.2595 - mae: 0.1256
Epoch 10/100
10/10 [==============================] - 0s 9ms/step - loss: 4.6274 - mae: 0.1250
Epoch 11/100
10/10 [==============================] -

In [15]:
model(X[:10])

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[ 1.8181489 ],
       [ 1.3753326 ],
       [ 0.74320513],
       [ 0.18449138],
       [ 0.17746694],
       [-0.01034747],
       [ 1.6917394 ],
       [ 1.5771424 ],
       [ 0.9553767 ],
       [ 0.4491061 ]], dtype=float32)>

In [16]:
y[:10]

array([[1.98928434],
       [1.56662308],
       [0.79653985],
       [0.29722255],
       [0.31835771],
       [0.1342613 ],
       [1.86049776],
       [1.54321869],
       [1.14029437],
       [0.51089068]])

In [17]:
X_test = np.random.uniform(size=(5, 4))
y_test = np.expand_dims(X_test[:, 0]*2 - X_test[:, 1]**3 + X_test[:, 2]/3, -1)
y_test

array([[0.37988603],
       [0.87364403],
       [0.67920417],
       [0.87606582],
       [1.44801915]])

In [18]:
model(X_test)

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[0.3065448 ],
       [0.6748702 ],
       [0.77083594],
       [1.0488328 ],
       [1.4986001 ]], dtype=float32)>

# Classification

## Binary

In [19]:
X = np.random.uniform(size=(10000, 4))

X[:10]

array([[0.6046829 , 0.8887141 , 0.60408035, 0.02335847],
       [0.43328228, 0.61925601, 0.30984098, 0.28164268],
       [0.27418638, 0.6152587 , 0.72116251, 0.36907444],
       [0.77073431, 0.47236772, 0.37290028, 0.1210173 ],
       [0.83827061, 0.96538411, 0.14166915, 0.08348426],
       [0.92178636, 0.49298199, 0.61708619, 0.45614973],
       [0.72935387, 0.26165974, 0.16762862, 0.64948416],
       [0.0425525 , 0.76708917, 0.84341216, 0.71016   ],
       [0.49452314, 0.73971038, 0.0046099 , 0.93952114],
       [0.06888139, 0.60003036, 0.67734341, 0.25532111]])

In [20]:
y = np.expand_dims((X[:, 0] > .3).astype(np.float32), -1)

y[:10]

array([[1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.]], dtype=float32)

In [21]:
data = tf.data.Dataset.from_tensor_slices((X, y)).batch(1000)
data

<BatchDataset element_spec=(TensorSpec(shape=(None, 4), dtype=tf.float64, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))>

In [22]:
model = tf.keras.Sequential()

number_masks = 2
steps = [StepNoFeedback(AllOnesMaskedInputNoFeedback(number_masks),
                        LinearSeparators(),
                        PredictionNeurons(units=1)),
         StepWithFeedback(AllOnesMaskedInputWithFeedback(number_masks=number_masks),
                          LinearSeparators(),
                          PredictionNeurons(units=1))]
    
model.add(LorisNetLayer(steps=steps,
                        weighted_addition=NormalizedWeightedAdd(),
                        activation = 'sigmoid'
                       ))

model.compile(loss= tf.keras.losses.BinaryCrossentropy(),
              optimizer=tf.keras.optimizers.Adam(learning_rate=.01),
              metrics=['accuracy'])

history = model.fit(data,
                    epochs=100,
                    verbose=1)

Epoch 1/100
10/10 [==============================] - 2s 5ms/step - loss: 1.2092 - accuracy: 0.3038
Epoch 2/100
10/10 [==============================] - 0s 5ms/step - loss: 0.8128 - accuracy: 0.3038
Epoch 3/100
10/10 [==============================] - 0s 5ms/step - loss: 0.7746 - accuracy: 0.3038
Epoch 4/100
10/10 [==============================] - 0s 5ms/step - loss: 0.7352 - accuracy: 0.3038
Epoch 5/100
10/10 [==============================] - 0s 5ms/step - loss: 0.6966 - accuracy: 0.3394
Epoch 6/100
10/10 [==============================] - 0s 5ms/step - loss: 0.6605 - accuracy: 0.7928
Epoch 7/100
10/10 [==============================] - 0s 5ms/step - loss: 0.6277 - accuracy: 0.9319
Epoch 8/100
10/10 [==============================] - 0s 6ms/step - loss: 0.5987 - accuracy: 0.8560
Epoch 9/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5732 - accuracy: 0.7888
Epoch 10/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5508 - accuracy: 0.7627
Epoch 11/

In [23]:
X_test = [[.9, .1, .1, .1], [.1, .1, .1, .1]]
model.predict(X_test)

1/1 [==============================] - 0s 320ms/step


array([[0.97659445],
       [0.02515772]], dtype=float32)

## Multi-classes

In [24]:
X

array([[0.6046829 , 0.8887141 , 0.60408035, 0.02335847],
       [0.43328228, 0.61925601, 0.30984098, 0.28164268],
       [0.27418638, 0.6152587 , 0.72116251, 0.36907444],
       ...,
       [0.81968175, 0.18314178, 0.31132648, 0.411138  ],
       [0.48538382, 0.29802114, 0.655289  , 0.27585958],
       [0.42123771, 0.13574827, 0.01055755, 0.65751249]])

In [25]:
y0_indicator = np.expand_dims((X[:, 1] < .5).astype(np.float32), -1)
y1_indicator = np.expand_dims(np.logical_and(X[:, 1] >= .5, X[:, 0] <= .5).astype(np.float32), -1)
y2_indicator = np.expand_dims(np.logical_and(X[:, 1] >= .5, X[:, 0] > .5).astype(np.float32), -1)

In [26]:
y = np.concatenate((y0_indicator, y1_indicator, y2_indicator), -1)
y

array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [27]:
data = tf.data.Dataset.from_tensor_slices((X, y)).batch(1000)
data

<BatchDataset element_spec=(TensorSpec(shape=(None, 4), dtype=tf.float64, name=None), TensorSpec(shape=(None, 3), dtype=tf.float32, name=None))>

In [28]:
model = tf.keras.Sequential()

number_masks = 2
steps = [StepNoFeedback(AllOnesMaskedInputNoFeedback(number_masks),
                        LinearSeparators(),
                        PredictionNeurons(units=3)),
         StepWithFeedback(AllOnesMaskedInputWithFeedback(number_masks=number_masks),
                          LinearSeparators(),
                          PredictionNeurons(units=3))]
    
model.add(LorisNetLayer(steps=steps,
                        weighted_addition=NormalizedWeightedAdd(),
                        activation='softmax'
                       ))

model.compile(loss= tf.keras.losses.CategoricalCrossentropy(),
              optimizer=tf.keras.optimizers.Adam(learning_rate=.01),
              metrics=['accuracy'])

history = model.fit(data,
                    epochs=100,
                    verbose=1)

Epoch 1/100
10/10 [==============================] - 2s 7ms/step - loss: 1.0243 - accuracy: 0.5044
Epoch 2/100
10/10 [==============================] - 0s 7ms/step - loss: 0.9423 - accuracy: 0.5044
Epoch 3/100
10/10 [==============================] - 0s 7ms/step - loss: 0.8757 - accuracy: 0.5206
Epoch 4/100
10/10 [==============================] - 0s 6ms/step - loss: 0.8286 - accuracy: 0.5598
Epoch 5/100
10/10 [==============================] - 0s 7ms/step - loss: 0.7814 - accuracy: 0.5984
Epoch 6/100
10/10 [==============================] - 0s 7ms/step - loss: 0.7274 - accuracy: 0.7365
Epoch 7/100
10/10 [==============================] - 0s 7ms/step - loss: 0.6686 - accuracy: 0.8402
Epoch 8/100
10/10 [==============================] - 0s 7ms/step - loss: 0.6062 - accuracy: 0.8706
Epoch 9/100
10/10 [==============================] - 0s 7ms/step - loss: 0.5456 - accuracy: 0.9167
Epoch 10/100
10/10 [==============================] - 0s 6ms/step - loss: 0.4899 - accuracy: 0.9437
Epoch 11/

In [29]:
X_test = [[.1, .1, .1, .1], [.1, .9, .1, .1], [.9, .9, .1, .1]]
model.predict(X_test)

1/1 [==============================] - 0s 291ms/step


array([[9.9083978e-01, 8.9483075e-03, 2.1182070e-04],
       [8.8660419e-03, 9.8637968e-01, 4.7542518e-03],
       [1.0753012e-02, 5.5836127e-03, 9.8366326e-01]], dtype=float32)