In [1]:
import tensorflow as tf
from LorisNet import *

In [2]:
X = tf.cast(tf.random.uniform((3, 2, 2)) <= .5,
            dtype=tf.float32)

X

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[1., 0.],
        [1., 1.]],

       [[1., 1.],
        [1., 0.]],

       [[0., 0.],
        [0., 1.]]], dtype=float32)>

In [3]:
l = PredictionNeurons()

l(X)

<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[-0.70212334],
        [ 0.9304714 ]],

       [[-0.20372277],
        [-0.15751612]],

       [[ 0.        ],
        [ 1.0879875 ]]], dtype=float32)>

In [4]:
l.kernel

<tf.Variable 'prediction_neurons/prediction_kernel:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.70212334,  0.49840057],
       [-0.15751612,  1.0879875 ]], dtype=float32)>