In [1]:
from LorisNet import *
import tensorflow as tf

In [2]:
X = tf.random.uniform((3, 2))

X

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.12380397, 0.74558747],
       [0.9988195 , 0.12075651],
       [0.43620515, 0.8927796 ]], dtype=float32)>

In [3]:
s = StepNoFeedback(AllOnesMaskedInputNoFeedback(4),
                   LinearSeparators(),
                   PredictionNeurons()
                  )

s(X)

(<tf.Tensor: shape=(3, 4, 1), dtype=float32, numpy=
 array([[[-0.4335525 ],
         [ 0.38156664],
         [ 0.4089815 ],
         [-0.07941826]],
 
        [[-0.22876315],
         [ 0.35606474],
         [ 0.22395948],
         [-0.05978992]],
 
        [[-0.40679783],
         [ 0.41258284],
         [ 0.3801137 ],
         [-0.08168785]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>)

In [4]:
prior_masks = tf.random.uniform((3, 4, 5, 2))  # nbr samples, nbr masks, nbr prior masks, input dim

prior_masks

<tf.Tensor: shape=(3, 5, 4, 2), dtype=float32, numpy=
array([[[[7.45322585e-01, 8.27507019e-01],
         [3.61589193e-01, 4.75033522e-01],
         [5.64318657e-01, 3.90518427e-01],
         [7.48401999e-01, 7.92961240e-01]],

        [[9.23538327e-01, 4.30093884e-01],
         [2.47704029e-01, 3.58657002e-01],
         [2.09444165e-01, 9.05783176e-01],
         [3.91398311e-01, 3.70508432e-02]],

        [[8.64222288e-01, 3.66685390e-01],
         [1.80832982e-01, 8.82886767e-01],
         [8.74152541e-01, 8.73106599e-01],
         [7.45058417e-01, 9.95392084e-01]],

        [[1.89658046e-01, 2.54750252e-04],
         [3.65193248e-01, 3.39095950e-01],
         [6.14681602e-01, 6.41161442e-01],
         [5.81745625e-01, 3.59641433e-01]],

        [[9.86349702e-01, 4.03743029e-01],
         [4.78948355e-02, 6.98472261e-02],
         [6.83986902e-01, 4.05567288e-01],
         [5.06648421e-01, 7.26957083e-01]]],


       [[[4.13180470e-01, 2.30252743e-01],
         [1.16362691e-01, 5.980

In [5]:
prior_spacial_indicators = tf.random.uniform((3, 4, 5))

prior_spacial_indicators

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0.5870639 , 0.8329872 , 0.2226671 , 0.8066822 , 0.38511407],
        [0.5610932 , 0.84535336, 0.34175277, 0.0142045 , 0.06213951],
        [0.92565274, 0.30584574, 0.67993724, 0.6584364 , 0.22483015],
        [0.55732775, 0.34397316, 0.96235466, 0.5587491 , 0.34058   ]],

       [[0.96849656, 0.00669527, 0.61949   , 0.4917097 , 0.14902937],
        [0.18968856, 0.04633081, 0.32505393, 0.63678145, 0.80369484],
        [0.7502737 , 0.7749826 , 0.24587524, 0.01835287, 0.94390476],
        [0.6198822 , 0.1451317 , 0.943643  , 0.19931364, 0.68265676]],

       [[0.3634001 , 0.55613065, 0.6072962 , 0.68301284, 0.25696182],
        [0.841593  , 0.76666653, 0.34733474, 0.00785863, 0.01363051],
        [0.71556675, 0.79696906, 0.9713284 , 0.73863006, 0.7918339 ],
        [0.88110375, 0.67984855, 0.0998323 , 0.38456273, 0.53743315]]],
      dtype=float32)>

In [6]:
s = StepWithFeedback(AllOnesMaskedInputWithFeedback(4),
                     LinearSeparators(),
                     PredictionNeurons()
                    )

s([X, prior_masks, prior_spacial_indicators])

(<tf.Tensor: shape=(3, 4, 1), dtype=float32, numpy=
 array([[[ 0.02668411],
         [ 0.04541416],
         [ 0.93738866],
         [ 0.27324378]],
 
        [[-0.7815631 ],
         [ 0.62423277],
         [ 1.6380196 ],
         [ 0.39389217]],
 
        [[-0.08783379],
         [ 0.24470423],
         [ 1.2325513 ],
         [ 1.2008983 ]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4, 1), dtype=float32, numpy=
 array([[[0.4804108 ],
         [0.45030534],
         [0.5075    ],
         [0.38558176]],
 
        [[0.34204504],
         [0.65305644],
         [0.69848263],
         [0.52549684]],
 
        [[0.42981488],
         [0.48919666],
         [0.5699516 ],
         [0.37620884]]], dtype=float32)>)