In [1]:
from LorisNet import *
import tensorflow as tf

In [2]:
X = tf.random.uniform((3, 2))

X

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.01704586, 0.91344154],
       [0.48964906, 0.63008714],
       [0.48784328, 0.23413813]], dtype=float32)>

In [3]:
prior_masks = tf.random.uniform((4, 5, 2))  # nbr masks, nbr prior masks, input dim

prior_masks

<tf.Tensor: shape=(4, 5, 2), dtype=float32, numpy=
array([[[6.3600814e-01, 2.1812630e-01],
        [8.3894789e-01, 6.2532008e-01],
        [6.5442443e-02, 2.0542622e-01],
        [1.5109539e-02, 7.8840303e-01],
        [7.7596068e-01, 1.6536677e-01]],

       [[3.8995528e-01, 6.7402124e-03],
        [1.3308954e-01, 5.4337513e-01],
        [8.3219957e-01, 5.9641182e-01],
        [2.0390284e-01, 7.5953579e-01],
        [2.8955686e-01, 7.5956869e-01]],

       [[4.9723506e-02, 6.8365288e-01],
        [4.1660345e-01, 8.7833405e-04],
        [5.8449256e-01, 8.0304062e-01],
        [7.0075321e-01, 4.7432566e-01],
        [9.8321319e-01, 1.4646876e-01]],

       [[7.6885760e-01, 7.8350830e-01],
        [3.1156576e-01, 7.4745452e-01],
        [4.8423803e-01, 7.4649346e-01],
        [7.1888494e-01, 9.0110683e-01],
        [4.2227399e-01, 3.8295436e-01]]], dtype=float32)>

In [4]:
SigmoidMaskedInputNoFeedback(4)(X)

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.00892057, 0.28317893],
         [0.01197616, 0.61978644],
         [0.00494574, 0.6202352 ],
         [0.00730111, 0.3020134 ]],
 
        [[0.25624692, 0.19533533],
         [0.34402016, 0.42752543],
         [0.14206849, 0.42783496],
         [0.2097272 , 0.20832723]],
 
        [[0.2553019 , 0.07258591],
         [0.34275144, 0.15886693],
         [0.14154455, 0.15898195],
         [0.20895374, 0.07741366]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0.5233277 , 0.3100132 ],
        [0.70258516, 0.67851794],
        [0.2901435 , 0.6790092 ],
        [0.42832145, 0.33063242]], dtype=float32)>)

In [5]:
SigmoidMaskedInputWithFeedback(4)([X, prior_masks])

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.01127826, 0.5859554 ],
         [0.00531972, 0.29577842],
         [0.00505335, 0.6543356 ],
         [0.00736207, 0.29011247]],
 
        [[0.32397264, 0.4041889 ],
         [0.1528112 , 0.20402639],
         [0.14515951, 0.45135728],
         [0.21147832, 0.20011805]],
 
        [[0.32277787, 0.15019515],
         [0.15224764, 0.07581548],
         [0.14462417, 0.16772275],
         [0.2106984 , 0.07436315]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0.66164255, 0.641481  ],
        [0.3120831 , 0.3238066 ],
        [0.29645622, 0.716341  ],
        [0.43189773, 0.31760377]], dtype=float32)>)

In [6]:
SoftmaxMaskedInputNoFeedback(4)(X)

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.00395784, 0.70135146],
         [0.00713582, 0.53105235],
         [0.00607337, 0.58798623],
         [0.01213505, 0.26315662]],
 
        [[0.1136906 , 0.48378852],
         [0.20497921, 0.3663171 ],
         [0.17445987, 0.4055898 ],
         [0.34858432, 0.18152405]],
 
        [[0.11327132, 0.17977409],
         [0.20422328, 0.13612212],
         [0.17381647, 0.15071572],
         [0.34729877, 0.06745369]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0.23218793, 0.7678121 ],
        [0.41862476, 0.5813753 ],
        [0.35629573, 0.6437043 ],
        [0.71190643, 0.28809357]], dtype=float32)>)

In [7]:
SoftmaxMaskedInputWithFeedback(4)([X, prior_masks])

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.00823549, 0.4721236 ],
         [0.00317958, 0.7430563 ],
         [0.01038453, 0.35696238],
         [0.01223896, 0.25758842]],
 
        [[0.2365679 , 0.32566833],
         [0.09133474, 0.5125563 ],
         [0.29829988, 0.24623077],
         [0.35156915, 0.17768313]],
 
        [[0.23569547, 0.1210172 ],
         [0.0909979 , 0.1904641 ],
         [0.29719976, 0.09149847],
         [0.3502726 , 0.06602642]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0.48313767, 0.5168624 ],
        [0.18653102, 0.81346893],
        [0.60921156, 0.39078844],
        [0.7180023 , 0.2819977 ]], dtype=float32)>)

In [8]:
FracOnesMaskedInputNoFeedback(4, .5)(X)

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.        , 0.        ],
         [0.        , 0.91344154],
         [0.        , 0.        ],
         [0.01704586, 0.        ]],
 
        [[0.        , 0.        ],
         [0.        , 0.63008714],
         [0.        , 0.        ],
         [0.48964906, 0.        ]],
 
        [[0.        , 0.        ],
         [0.        , 0.23413813],
         [0.        , 0.        ],
         [0.48784328, 0.        ]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0., 0.],
        [0., 1.],
        [0., 0.],
        [1., 0.]], dtype=float32)>)

In [9]:
FracOnesMaskedInputWithFeedback(4, .5)([X, prior_masks])

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.01704586, 0.91344154],
         [0.01704586, 0.91344154],
         [0.01704586, 0.91344154],
         [0.01704586, 0.91344154]],
 
        [[0.48964906, 0.63008714],
         [0.48964906, 0.63008714],
         [0.48964906, 0.63008714],
         [0.48964906, 0.63008714]],
 
        [[0.48784328, 0.23413813],
         [0.48784328, 0.23413813],
         [0.48784328, 0.23413813],
         [0.48784328, 0.23413813]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>)

In [10]:
AllOnesMaskedInputNoFeedback(4)(X)

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.01704586, 0.91344154],
         [0.01704586, 0.91344154],
         [0.01704586, 0.91344154],
         [0.01704586, 0.91344154]],
 
        [[0.48964906, 0.63008714],
         [0.48964906, 0.63008714],
         [0.48964906, 0.63008714],
         [0.48964906, 0.63008714]],
 
        [[0.48784328, 0.23413813],
         [0.48784328, 0.23413813],
         [0.48784328, 0.23413813],
         [0.48784328, 0.23413813]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>)

In [11]:
AllOnesMaskedInputWithFeedback(4)([X, prior_masks])

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.01704586, 0.91344154],
         [0.01704586, 0.91344154],
         [0.01704586, 0.91344154],
         [0.01704586, 0.91344154]],
 
        [[0.48964906, 0.63008714],
         [0.48964906, 0.63008714],
         [0.48964906, 0.63008714],
         [0.48964906, 0.63008714]],
 
        [[0.48784328, 0.23413813],
         [0.48784328, 0.23413813],
         [0.48784328, 0.23413813],
         [0.48784328, 0.23413813]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>)

In [12]:
RandomMaskedInputNoFeedback(4)(X)

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.0023104 , 0.75335485],
         [0.01298574, 0.17219281],
         [0.0132488 , 0.16431086],
         [0.00736878, 0.6193334 ]],
 
        [[0.06636704, 0.5196602 ],
         [0.37302056, 0.11877769],
         [0.38057712, 0.11334077],
         [0.21167113, 0.4272129 ]],
 
        [[0.06612228, 0.19310388],
         [0.3716449 , 0.04413737],
         [0.3791736 , 0.04211702],
         [0.2108905 , 0.15875079]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0.13554001, 0.8247434 ],
        [0.7618121 , 0.18850994],
        [0.7772447 , 0.1798811 ],
        [0.4322915 , 0.6780219 ]], dtype=float32)>)

In [13]:
RandomMaskedInputWithFeedback(4)([X, prior_masks])

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.00708336, 0.8814121 ],
         [0.01048479, 0.73423856],
         [0.01307732, 0.86237776],
         [0.00572465, 0.62218183]],
 
        [[0.20347232, 0.6079934 ],
         [0.30117995, 0.5064739 ],
         [0.37565133, 0.59486365],
         [0.16444275, 0.42917773]],
 
        [[0.20272194, 0.22592817],
         [0.3000692 , 0.18820389],
         [0.37426597, 0.2210492 ],
         [0.16383629, 0.15948091]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0.41554725, 0.9649354 ],
        [0.61509347, 0.8038156 ],
        [0.76718485, 0.9440974 ],
        [0.33583796, 0.6811403 ]], dtype=float32)>)