In [13]:
import tensorflow as tf
from LorisNet import *

In [10]:
X = tf.random.uniform((3, 4, 1))
X

<tf.Tensor: shape=(3, 4, 1), dtype=float32, numpy=
array([[[0.84606504],
        [0.02131128],
        [0.84051085],
        [0.791612  ]],

       [[0.45507383],
        [0.24944854],
        [0.46842623],
        [0.276263  ]],

       [[0.65310025],
        [0.44818735],
        [0.3366964 ],
        [0.8964248 ]]], dtype=float32)>

In [11]:
l = WeightedAdd()

l(X)

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[-0.33683312],
       [-0.5813599 ],
       [-0.11420575]], dtype=float32)>

In [12]:
l.kernel

<tf.Variable 'weighted_add_1/kernel:0' shape=(4, 1) dtype=float32, numpy=
array([[-0.46251726],
       [-0.97589487],
       [-0.87789726],
       [ 1.0272284 ]], dtype=float32)>

In [6]:
0.81953156*-1.0177766 + 0.3596604*0.7693356 + 0.16301131*-0.54598784 + 0.6038375*0.17819464

-0.5388020822107263

In [2]:
X = tf.random.uniform((3, 4, 2))
X

<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
array([[[0.3915758 , 0.39437473],
        [0.10638332, 0.17912292],
        [0.9923787 , 0.6467385 ],
        [0.71825004, 0.3257544 ]],

       [[0.9105991 , 0.9461776 ],
        [0.637347  , 0.36591125],
        [0.90101874, 0.31471014],
        [0.8675045 , 0.83666587]],

       [[0.80469584, 0.07335424],
        [0.6214094 , 0.13312519],
        [0.53154385, 0.9789301 ],
        [0.2887534 , 0.18036878]]], dtype=float32)>

In [3]:
l = WeightedAdd()

l(X)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.5219473 , -0.19287026],
       [-0.67656624, -0.6419726 ],
       [-0.1734155 , -0.0788793 ]], dtype=float32)>

In [4]:
l.kernel

<tf.Variable 'weighted_add/kernel:0' shape=(4, 1) dtype=float32, numpy=
array([[ 0.23814774],
       [-0.22937495],
       [ 0.11312532],
       [-0.9788537 ]], dtype=float32)>

In [5]:
0.9105991*0.23814774 + 0.637347*-0.22937495 + 0.90101874*0.11312532 + 0.8675045*-0.9788537

-0.6765662748497693

In [6]:
0.9461776*0.23814774 + 0.36591125*-0.22937495 + 0.31471014*0.11312532 + 0.83666587*-0.9788537

-0.6419726148130378