In [1]:
from LorisNet import *
import tensorflow as tf

In [2]:
X = tf.random.uniform((3, 2))

X

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.29457104, 0.17625213],
       [0.14131105, 0.10600519],
       [0.43496895, 0.20234561]], dtype=float32)>

In [3]:
prior_masks = tf.random.uniform((4, 5, 2))  # nbr masks, nbr prior masks, input dim

prior_masks

<tf.Tensor: shape=(4, 5, 2), dtype=float32, numpy=
array([[[0.425084  , 0.5526043 ],
        [0.27846718, 0.1096046 ],
        [0.89013565, 0.8725954 ],
        [0.718861  , 0.5881225 ],
        [0.8440119 , 0.03376806]],

       [[0.04182279, 0.76367414],
        [0.84270215, 0.1782974 ],
        [0.9732667 , 0.60763717],
        [0.48093963, 0.24165833],
        [0.8466196 , 0.92005193]],

       [[0.37466633, 0.2642815 ],
        [0.8465402 , 0.4377774 ],
        [0.51724696, 0.7409941 ],
        [0.79610777, 0.46706462],
        [0.91728425, 0.34923697]],

       [[0.21709847, 0.12265658],
        [0.21439648, 0.43175817],
        [0.12425125, 0.37987292],
        [0.1598754 , 0.15160978],
        [0.66287637, 0.10355556]]], dtype=float32)>

In [4]:
SigmoidMaskedInputNoFeedback(4)(X)

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.15547355, 0.10322578],
         [0.08931935, 0.0873716 ],
         [0.16860314, 0.12099452],
         [0.17372386, 0.06610066]],
 
        [[0.07458347, 0.06208418],
         [0.04284811, 0.05254883],
         [0.08088197, 0.07277102],
         [0.08333848, 0.03975562]],
 
        [[0.22957507, 0.11850798],
         [0.13189058, 0.10030665],
         [0.24896245, 0.13890733],
         [0.25652382, 0.07588662]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0.52779645, 0.5856711 ],
        [0.30321836, 0.49571943],
        [0.5723683 , 0.68648547],
        [0.589752  , 0.3750347 ]], dtype=float32)>)

In [5]:
SigmoidMaskedInputWithFeedback(4)([X, prior_masks])

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.12761387, 0.11900552],
         [0.1304569 , 0.11846469],
         [0.16267815, 0.06320681],
         [0.17733698, 0.09015307]],
 
        [[0.06121868, 0.07157476],
         [0.06258253, 0.07124949],
         [0.07803965, 0.03801515],
         [0.08507175, 0.05422172]],
 
        [[0.18843696, 0.13662384],
         [0.19263501, 0.13600296],
         [0.24021351, 0.07256436],
         [0.261859  , 0.1034999 ]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0.43321934, 0.67520046],
        [0.44287074, 0.672132  ],
        [0.5522544 , 0.3586159 ],
        [0.6020177 , 0.5115006 ]], dtype=float32)>)

In [6]:
SoftmaxMaskedInputNoFeedback(4)(X)

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.08301196, 0.12658317],
         [0.21015348, 0.05050996],
         [0.10107295, 0.11577665],
         [0.1188712 , 0.10512733]],
 
        [[0.03982233, 0.07613227],
         [0.10081442, 0.03037874],
         [0.04848652, 0.06963278],
         [0.05702466, 0.06322785]],
 
        [[0.12257696, 0.14532335],
         [0.31031644, 0.05798778],
         [0.14924616, 0.13291696],
         [0.17552738, 0.12069105]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0.28180623, 0.71819377],
        [0.71342206, 0.28657788],
        [0.3431191 , 0.65688086],
        [0.40354002, 0.5964599 ]], dtype=float32)>)

In [7]:
SoftmaxMaskedInputWithFeedback(4)([X, prior_masks])

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.18806827, 0.06372432],
         [0.17425139, 0.07199144],
         [0.14102511, 0.09187189],
         [0.18758117, 0.06401578]],
 
        [[0.09021975, 0.0383264 ],
         [0.08359154, 0.04329858],
         [0.06765229, 0.05525548],
         [0.08998608, 0.03850169]],
 
        [[0.27770504, 0.07315848],
         [0.25730276, 0.08264951],
         [0.20824024, 0.10547318],
         [0.27698576, 0.07349308]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0.63844794, 0.3615521 ],
        [0.59154284, 0.40845716],
        [0.47874737, 0.52125263],
        [0.6367943 , 0.3632057 ]], dtype=float32)>)

In [8]:
FracOnesMaskedInputNoFeedback(4, .5)(X)

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.29457104, 0.17625213],
         [0.29457104, 0.        ],
         [0.        , 0.        ],
         [0.        , 0.17625213]],
 
        [[0.14131105, 0.10600519],
         [0.14131105, 0.        ],
         [0.        , 0.        ],
         [0.        , 0.10600519]],
 
        [[0.43496895, 0.20234561],
         [0.43496895, 0.        ],
         [0.        , 0.        ],
         [0.        , 0.20234561]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 0.],
        [0., 0.],
        [0., 1.]], dtype=float32)>)

In [9]:
FracOnesMaskedInputWithFeedback(4, .5)([X, prior_masks])

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.        , 0.        ],
         [0.29457104, 0.17625213],
         [0.        , 0.17625213],
         [0.        , 0.17625213]],
 
        [[0.        , 0.        ],
         [0.14131105, 0.10600519],
         [0.        , 0.10600519],
         [0.        , 0.10600519]],
 
        [[0.        , 0.        ],
         [0.43496895, 0.20234561],
         [0.        , 0.20234561],
         [0.        , 0.20234561]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0., 0.],
        [1., 1.],
        [0., 1.],
        [0., 1.]], dtype=float32)>)

In [10]:
AllOnesMaskedInputNoFeedback(4)(X)

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.29457104, 0.17625213],
         [0.29457104, 0.17625213],
         [0.29457104, 0.17625213],
         [0.29457104, 0.17625213]],
 
        [[0.14131105, 0.10600519],
         [0.14131105, 0.10600519],
         [0.14131105, 0.10600519],
         [0.14131105, 0.10600519]],
 
        [[0.43496895, 0.20234561],
         [0.43496895, 0.20234561],
         [0.43496895, 0.20234561],
         [0.43496895, 0.20234561]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>)

In [11]:
AllOnesMaskedInputWithFeedback(4)([X, prior_masks])

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.29457104, 0.17625213],
         [0.29457104, 0.17625213],
         [0.29457104, 0.17625213],
         [0.29457104, 0.17625213]],
 
        [[0.14131105, 0.10600519],
         [0.14131105, 0.10600519],
         [0.14131105, 0.10600519],
         [0.14131105, 0.10600519]],
 
        [[0.43496895, 0.20234561],
         [0.43496895, 0.20234561],
         [0.43496895, 0.20234561],
         [0.43496895, 0.20234561]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>)

In [12]:
RandomMaskedInputNoFeedback(4)(X)

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[1.89964637e-01, 7.40929544e-02],
         [2.38956004e-01, 7.70738721e-02],
         [1.58783078e-01, 8.74380395e-02],
         [5.32801338e-02, 4.36123053e-04]],
 
        [[9.11294669e-02, 4.45625111e-02],
         [1.14631511e-01, 4.63553593e-02],
         [7.61711076e-02, 5.25887907e-02],
         [2.55594421e-02, 2.62302143e-04]],
 
        [[2.80505240e-01, 8.50621462e-02],
         [3.52846771e-01, 8.84843767e-02],
         [2.34461963e-01, 1.00382924e-01],
         [7.86744133e-02, 5.00689493e-04]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0.64488566, 0.42038047],
        [0.8111999 , 0.4372933 ],
        [0.5390315 , 0.49609637],
        [0.18087363, 0.00247443]], dtype=float32)>)

In [13]:
RandomMaskedInputWithFeedback(4)([X, prior_masks])

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.11937121, 0.08637474],
         [0.28269938, 0.07627258],
         [0.28693417, 0.01248803],
         [0.28571066, 0.13519967]],
 
        [[0.05726453, 0.05194928],
         [0.13561599, 0.04587343],
         [0.13764751, 0.00751081],
         [0.13706057, 0.08131457]],
 
        [[0.1762657 , 0.09916221],
         [0.417439  , 0.08756445],
         [0.4236922 , 0.01433684],
         [0.42188558, 0.15521547]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0.40523744, 0.49006355],
        [0.95969844, 0.432747  ],
        [0.9740746 , 0.07085323],
        [0.9699211 , 0.767081  ]], dtype=float32)>)

In [14]:
masks = tf.random.uniform((4, 2))
masks

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[0.74445665, 0.08375955],
       [0.38694477, 0.5415486 ],
       [0.18022668, 0.8081273 ],
       [0.22822833, 0.3011979 ]], dtype=float32)>

In [15]:
DeterminedMaskedInputNoFeedback(masks)(X)

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.21929537, 0.0147628 ],
         [0.11398272, 0.0954491 ],
         [0.05308956, 0.14243415],
         [0.06722946, 0.05308677]],
 
        [[0.10519995, 0.00887895],
         [0.05467957, 0.05740697],
         [0.02546802, 0.08566569],
         [0.03225119, 0.03192854]],
 
        [[0.32381552, 0.01694838],
         [0.16830896, 0.10957998],
         [0.07839301, 0.163521  ],
         [0.09927224, 0.06094607]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0.74445665, 0.08375955],
        [0.38694477, 0.5415486 ],
        [0.18022668, 0.8081273 ],
        [0.22822833, 0.3011979 ]], dtype=float32)>)

In [16]:
DeterminedMaskedInputWithFeedback(masks)([X, prior_masks])

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.21929537, 0.0147628 ],
         [0.11398272, 0.0954491 ],
         [0.05308956, 0.14243415],
         [0.06722946, 0.05308677]],
 
        [[0.10519995, 0.00887895],
         [0.05467957, 0.05740697],
         [0.02546802, 0.08566569],
         [0.03225119, 0.03192854]],
 
        [[0.32381552, 0.01694838],
         [0.16830896, 0.10957998],
         [0.07839301, 0.163521  ],
         [0.09927224, 0.06094607]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0.74445665, 0.08375955],
        [0.38694477, 0.5415486 ],
        [0.18022668, 0.8081273 ],
        [0.22822833, 0.3011979 ]], dtype=float32)>)