In [1]:
from LorisNet import *
import tensorflow as tf

In [2]:
X = tf.random.uniform((3, 2))

X

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.2421031 , 0.35309362],
       [0.5748199 , 0.2997818 ],
       [0.77098453, 0.5100765 ]], dtype=float32)>

In [3]:
s = StepNoFeedback(AllOnesMaskedInputNoFeedback(4),
                   LinearSeparators(),
                   PredictionNeurons()
                  )

s(X)

(<tf.Tensor: shape=(3, 4, 1), dtype=float32, numpy=
 array([[[-0.16230798],
         [ 0.09200797],
         [-0.0297331 ],
         [ 0.3608997 ]],
 
        [[-0.18682544],
         [ 0.08052108],
         [-0.02496391],
         [ 0.36609727]],
 
        [[-0.19301784],
         [ 0.06611964],
         [-0.02501376],
         [ 0.34439638]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4, 1), dtype=float32, numpy=
 array([[[0.5152721 ],
         [0.39689445],
         [0.52055734],
         [0.45386586]],
 
        [[0.5931066 ],
         [0.34734347],
         [0.43705985],
         [0.46040234]],
 
        [[0.6127654 ],
         [0.28522006],
         [0.43793273],
         [0.43311137]]], dtype=float32)>)

In [4]:
prior_masks = tf.random.uniform((4, 5, 2))  # nbr masks, nbr prior masks, input dim

prior_masks

<tf.Tensor: shape=(4, 5, 2), dtype=float32, numpy=
array([[[6.6631436e-01, 5.2636743e-02],
        [5.5149484e-01, 7.2762311e-01],
        [2.0756578e-01, 6.0176265e-01],
        [3.7809813e-01, 9.2873693e-02],
        [1.2737703e-01, 7.6140285e-02]],

       [[8.0842006e-01, 8.8106382e-01],
        [7.5038159e-01, 2.1830523e-01],
        [9.4378316e-01, 4.6865463e-01],
        [5.4643452e-01, 8.4877014e-05],
        [5.6567144e-01, 3.6465168e-02]],

       [[1.4692378e-01, 4.4754446e-01],
        [6.5853667e-01, 8.2133794e-01],
        [5.4055130e-01, 1.9880342e-01],
        [3.6226344e-01, 8.0358326e-01],
        [2.6640856e-01, 5.7882071e-03]],

       [[7.4201322e-01, 9.8172426e-03],
        [5.3524542e-01, 1.1505520e-01],
        [8.9622617e-01, 2.3636103e-02],
        [8.6917126e-01, 8.8179684e-01],
        [6.6400754e-01, 6.5974271e-01]]], dtype=float32)>

In [5]:
prior_spacial_indicators = tf.random.uniform((3, 4, 5))

prior_spacial_indicators

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0.15741503, 0.36818373, 0.20693767, 0.48318493, 0.19458234],
        [0.09094453, 0.23159707, 0.9383167 , 0.2325747 , 0.53208303],
        [0.98559344, 0.7204757 , 0.6219449 , 0.9655665 , 0.43991458],
        [0.08094406, 0.79372275, 0.11147308, 0.11628067, 0.21111667]],

       [[0.12134993, 0.800609  , 0.986372  , 0.33926368, 0.62208796],
        [0.7531278 , 0.29873133, 0.90100133, 0.81564   , 0.44145453],
        [0.2940756 , 0.26440895, 0.37807882, 0.9182757 , 0.01313305],
        [0.5963354 , 0.20085752, 0.62716556, 0.27764952, 0.14738321]],

       [[0.77049637, 0.7011156 , 0.8656794 , 0.9581324 , 0.9602606 ],
        [0.06418312, 0.8122184 , 0.20168781, 0.94971275, 0.07452154],
        [0.51996887, 0.38889956, 0.07291365, 0.13302279, 0.9431236 ],
        [0.10276484, 0.35562134, 0.11652529, 0.19484997, 0.04330909]]],
      dtype=float32)>

In [6]:
s = StepWithFeedback(AllOnesMaskedInputWithFeedback(4),
                     LinearSeparators(),
                     PredictionNeurons()
                    )

s([X, prior_masks, prior_spacial_indicators])

(<tf.Tensor: shape=(3, 4, 1), dtype=float32, numpy=
 array([[[-0.12196392],
         [-0.8422849 ],
         [-0.19291478],
         [ 0.27706605]],
 
        [[-0.02316923],
         [-1.086077  ],
         [ 0.15856098],
         [ 0.39009312]],
 
        [[ 0.07138112],
         [ 0.34220833],
         [-0.35076916],
         [ 0.15810238]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4, 1), dtype=float32, numpy=
 array([[[0.45373654],
         [0.4621562 ],
         [0.40907937],
         [0.5579287 ]],
 
        [[0.3774282 ],
         [0.40132412],
         [0.3521512 ],
         [0.5355518 ]],
 
        [[0.340903  ],
         [0.37087905],
         [0.29515335],
         [0.5679052 ]]], dtype=float32)>)