In [1]:
from LorisNet import *
import tensorflow as tf

In [2]:
X = tf.random.uniform((3, 4, 2))

X

<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
array([[[0.14782512, 0.76064694],
        [0.6554934 , 0.31566513],
        [0.2135582 , 0.64498234],
        [0.76735723, 0.48135757]],

       [[0.24809992, 0.6745708 ],
        [0.08744073, 0.79028773],
        [0.5970299 , 0.11864018],
        [0.45884395, 0.27129316]],

       [[0.15213287, 0.8642992 ],
        [0.07264805, 0.37042403],
        [0.93964076, 0.08017206],
        [0.54099846, 0.7547157 ]]], dtype=float32)>

In [3]:
l = LinearSeparators(activation=None)

In [4]:
l(X)

<tf.Tensor: shape=(3, 4, 1), dtype=float32, numpy=
array([[[-0.36936826],
        [ 0.05998242],
        [ 0.29106525],
        [ 0.11140318]],

       [[-0.36015964],
        [ 0.6186049 ],
        [-0.3971745 ],
        [ 0.07451023]],

       [[-0.41529056],
        [ 0.28040612],
        [-0.70168984],
        [-0.11979535]]], dtype=float32)>

In [5]:
l.kernel

<tf.Variable 'linear_separators/kernel:0' shape=(4, 2) dtype=float32, numpy=
array([[-0.27853775, -0.4314661 ],
       [-0.30151033,  0.81611943],
       [-0.8080971 ,  0.718843  ],
       [ 0.44471908, -0.4775145 ]], dtype=float32)>

In [6]:
l.bias

<tf.Variable 'linear_separators/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>

In [7]:
0.36560714*0.85120153 + 0.7953992*0.67046165

0.8444900169876042