In [1]:
from LorisNet import *
import tensorflow as tf

In [2]:
X = tf.random.uniform((3, 2))

X

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.15850115, 0.7566403 ],
       [0.0508014 , 0.17678547],
       [0.7601279 , 0.05344021]], dtype=float32)>

In [3]:
prior_masks = tf.random.uniform((3, 4, 5, 2))  # nbr samples, nbr masks, nbr prior masks, input dim

prior_masks

<tf.Tensor: shape=(3, 5, 4, 2), dtype=float32, numpy=
array([[[[0.59402716, 0.33935738],
         [0.9390849 , 0.12968278],
         [0.8505801 , 0.18328285],
         [0.21201563, 0.5855168 ]],

        [[0.46453297, 0.66443586],
         [0.19534588, 0.8053752 ],
         [0.522279  , 0.52214336],
         [0.43874264, 0.89798594]],

        [[0.32971668, 0.64977944],
         [0.06914294, 0.989082  ],
         [0.202672  , 0.35102034],
         [0.41564417, 0.59657204]],

        [[0.7473748 , 0.12871456],
         [0.5820404 , 0.9488728 ],
         [0.20098448, 0.5915183 ],
         [0.11677015, 0.6738868 ]],

        [[0.38553238, 0.6701721 ],
         [0.2951243 , 0.93550813],
         [0.90247285, 0.70605755],
         [0.22110343, 0.52675164]]],


       [[[0.4038545 , 0.7368028 ],
         [0.29114258, 0.30919743],
         [0.72735167, 0.84070706],
         [0.28155303, 0.4331478 ]],

        [[0.3874638 , 0.28664947],
         [0.04507852, 0.76075685],
         [0.43958855, 

In [4]:
SigmoidMaskedInputNoFeedback(4)(X)

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.09087455, 0.33381334],
         [0.1118552 , 0.21776225],
         [0.09978543, 0.3846148 ],
         [0.04933114, 0.44874084]],
 
        [[0.02912631, 0.07799393],
         [0.03585085, 0.05087913],
         [0.03198235, 0.08986345],
         [0.01581118, 0.10484619]],
 
        [[0.4358093 , 0.02357667],
         [0.5364268 , 0.01538018],
         [0.4785435 , 0.02716469],
         [0.23657855, 0.0316938 ]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0.57333684, 0.44117838],
        [0.70570594, 0.28780153],
        [0.62955654, 0.5083192 ],
        [0.3112352 , 0.5930702 ]], dtype=float32)>)

In [5]:
SigmoidMaskedInputWithFeedback(4)([X, prior_masks])

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.11392841, 0.20872699],
         [0.04807739, 0.38535503],
         [0.0909536 , 0.3172954 ],
         [0.07163234, 0.20609492]],
 
        [[0.03651533, 0.04876808],
         [0.01540934, 0.09003639],
         [0.02915165, 0.07413459],
         [0.02295897, 0.04815311]],
 
        [[0.5463693 , 0.01474203],
         [0.23056595, 0.02721697],
         [0.4361884 , 0.02241003],
         [0.34352902, 0.01455613]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0.718786  , 0.27586025],
        [0.3033252 , 0.5092975 ],
        [0.57383555, 0.41934773],
        [0.4519358 , 0.27238163]], dtype=float32)>)

In [6]:
SoftmaxMaskedInputNoFeedback(4)(X)

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.06823844, 0.430889  ],
         [0.05880385, 0.47592717],
         [0.0872518 , 0.34012452],
         [0.12063531, 0.18076101]],
 
        [[0.02187119, 0.1006752 ],
         [0.01884729, 0.11119816],
         [0.02796518, 0.0794685 ],
         [0.03866497, 0.04223396]],
 
        [[0.32725284, 0.03043295],
         [0.28200707, 0.03361392],
         [0.41843566, 0.02402241],
         [0.57853377, 0.01276684]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0.43052337, 0.56947666],
        [0.3709995 , 0.62900054],
        [0.5504806 , 0.44951943],
        [0.76110053, 0.23889951]], dtype=float32)>)

In [7]:
SoftmaxMaskedInputWithFeedback(4)([X, prior_masks])

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.12626415, 0.15389039],
         [0.03846013, 0.5730424 ],
         [0.06459904, 0.44826254],
         [0.07902581, 0.3793931 ]],
 
        [[0.04046908, 0.03595577],
         [0.0123269 , 0.13388868],
         [0.02070471, 0.10473445],
         [0.02532866, 0.08864342]],
 
        [[0.6055282 , 0.01086902],
         [0.18444419, 0.040473  ],
         [0.3097992 , 0.03166002],
         [0.37898606, 0.02679589]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0.7966135 , 0.20338646],
        [0.24264888, 0.7573511 ],
        [0.40756193, 0.5924381 ],
        [0.49858195, 0.50141805]], dtype=float32)>)

In [8]:
FracOnesMaskedInputNoFeedback(4, .5)(X)

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.15850115, 0.        ],
         [0.15850115, 0.7566403 ],
         [0.15850115, 0.        ],
         [0.        , 0.7566403 ]],
 
        [[0.0508014 , 0.        ],
         [0.0508014 , 0.17678547],
         [0.0508014 , 0.        ],
         [0.        , 0.17678547]],
 
        [[0.7601279 , 0.        ],
         [0.7601279 , 0.05344021],
         [0.7601279 , 0.        ],
         [0.        , 0.05344021]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[1., 0.],
        [1., 1.],
        [1., 0.],
        [0., 1.]], dtype=float32)>)

In [9]:
FracOnesMaskedInputWithFeedback(4, .5)([X, prior_masks])

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.        , 0.        ],
         [0.15850115, 0.7566403 ],
         [0.15850115, 0.        ],
         [0.        , 0.        ]],
 
        [[0.        , 0.        ],
         [0.0508014 , 0.17678547],
         [0.0508014 , 0.        ],
         [0.        , 0.        ]],
 
        [[0.        , 0.        ],
         [0.7601279 , 0.05344021],
         [0.7601279 , 0.        ],
         [0.        , 0.        ]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0., 0.],
        [1., 1.],
        [1., 0.],
        [0., 0.]], dtype=float32)>)

In [10]:
AllOnesMaskedInputNoFeedback(4)(X)

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.15850115, 0.7566403 ],
         [0.15850115, 0.7566403 ],
         [0.15850115, 0.7566403 ],
         [0.15850115, 0.7566403 ]],
 
        [[0.0508014 , 0.17678547],
         [0.0508014 , 0.17678547],
         [0.0508014 , 0.17678547],
         [0.0508014 , 0.17678547]],
 
        [[0.7601279 , 0.05344021],
         [0.7601279 , 0.05344021],
         [0.7601279 , 0.05344021],
         [0.7601279 , 0.05344021]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>)

In [11]:
AllOnesMaskedInputWithFeedback(4)([X, prior_masks])

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.15850115, 0.7566403 ],
         [0.15850115, 0.7566403 ],
         [0.15850115, 0.7566403 ],
         [0.15850115, 0.7566403 ]],
 
        [[0.0508014 , 0.17678547],
         [0.0508014 , 0.17678547],
         [0.0508014 , 0.17678547],
         [0.0508014 , 0.17678547]],
 
        [[0.7601279 , 0.05344021],
         [0.7601279 , 0.05344021],
         [0.7601279 , 0.05344021],
         [0.7601279 , 0.05344021]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>)

In [12]:
RandomMaskedInputNoFeedback(4)(X)

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.07477167, 0.13902953],
         [0.11737686, 0.59782964],
         [0.08660977, 0.23357078],
         [0.03747033, 0.23745726]],
 
        [[0.02396516, 0.0324836 ],
         [0.0376206 , 0.13968009],
         [0.0277594 , 0.05457272],
         [0.01200966, 0.05548078]],
 
        [[0.35858437, 0.00981942],
         [0.56290716, 0.04222368],
         [0.4153566 , 0.0164967 ],
         [0.17969741, 0.0167712 ]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0.47174215, 0.18374586],
        [0.74054265, 0.7901107 ],
        [0.5464299 , 0.3086946 ],
        [0.23640418, 0.3138311 ]], dtype=float32)>)

In [13]:
RandomMaskedInputWithFeedback(4)([X, prior_masks])

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[0.04712604, 0.34100538],
         [0.05526008, 0.33423147],
         [0.09752072, 0.56995386],
         [0.15032168, 0.65310687]],
 
        [[0.01510442, 0.07967431],
         [0.01771148, 0.07809162],
         [0.03125649, 0.13316704],
         [0.04817979, 0.15259537]],
 
        [[0.2260035 , 0.02408463],
         [0.26501215, 0.0236062 ],
         [0.46768254, 0.04025486],
         [0.7209014 , 0.04612783]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0.297323  , 0.4506836 ],
        [0.3486415 , 0.44173098],
        [0.61526823, 0.7532692 ],
        [0.9483949 , 0.8631669 ]], dtype=float32)>)