In [1]:
import tensorflow as tf
from LorisNet import *

In [2]:
X = tf.random.uniform((3, 4, 1))
X

<tf.Tensor: shape=(3, 4, 1), dtype=float32, numpy=
array([[[0.44635618],
        [0.13806379],
        [0.78494084],
        [0.03784037]],

       [[0.13098514],
        [0.77006435],
        [0.3633058 ],
        [0.7114589 ]],

       [[0.5066618 ],
        [0.5747522 ],
        [0.15514469],
        [0.11384344]]], dtype=float32)>

In [3]:
l = WeightedAdd()

l(X)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 0.04137606, -0.1986205 , -0.2702189 ], dtype=float32)>

In [4]:
l.kernel

<tf.Variable 'weighted_add/kernel:0' shape=(4,) dtype=float32, numpy=array([ 0.11397278, -0.6694254 ,  0.08733749,  0.37981278], dtype=float32)>