In [1]:
from LorisNet import *
import tensorflow as tf

In [2]:
X = tf.random.uniform((10000, 4))

X[:10]

<tf.Tensor: shape=(10, 4), dtype=float32, numpy=
array([[0.58511984, 0.01534379, 0.43919015, 0.4044757 ],
       [0.30837   , 0.09543407, 0.2317766 , 0.805418  ],
       [0.8765991 , 0.61005414, 0.3070644 , 0.9250845 ],
       [0.6953604 , 0.8505038 , 0.63232183, 0.94477904],
       [0.97954607, 0.14751208, 0.31538558, 0.3240341 ],
       [0.5754974 , 0.3155328 , 0.97568846, 0.47536373],
       [0.16417265, 0.5119536 , 0.00186765, 0.91655695],
       [0.6193384 , 0.16570055, 0.24693978, 0.6574887 ],
       [0.16632831, 0.9029299 , 0.10341728, 0.46818662],
       [0.79455924, 0.49603975, 0.25171375, 0.3334757 ]], dtype=float32)>

In [3]:
tmp = LorisNetLayer(steps=[StepNoFeedback(AllOnesMaskedInputNoFeedback(4),
                                          LinearSeparators(),
                                          PredictionNeurons()),
                           StepWithFeedback(AllOnesMaskedInputWithFeedback(4),
                                            LinearSeparators(),
                                            PredictionNeurons()),
                           StepWithFeedback(AllOnesMaskedInputWithFeedback(4),
                                            LinearSeparators(),
                                            PredictionNeurons()),
                           StepWithFeedback(AllOnesMaskedInputWithFeedback(4),
                                            LinearSeparators(),
                                            PredictionNeurons())],
                    weighted_addition=WeightedAdd(kernel_regularizer=tf.keras.regularizers.L2(l2=0.1))
                   )(X)

tmp[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.39135116, 0.4552787 , 0.3542242 , 0.53266335, 0.22070187,
       0.61722195, 0.46896565, 0.35056317, 0.5060353 , 0.29646724],
      dtype=float32)>

In [4]:
y = tf.expand_dims(tf.cast(X[:, 1] > .3, tf.float32) * 3 + 1, -1)

y[:10]

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [4.],
       [4.],
       [1.],
       [4.],
       [4.],
       [1.],
       [4.],
       [4.]], dtype=float32)>

In [25]:
model = tf.keras.Sequential()
model.add(LorisNetLayer(steps=[StepNoFeedback(AllOnesMaskedInputNoFeedback(100),
                                              LinearSeparators(),
                                              PredictionNeurons()),
                               StepWithFeedback(SigmoidMaskedInputWithFeedback(100),
                                                LinearSeparators(),
                                                PredictionNeurons()),
                               StepWithFeedback(FracOnesMaskedInputWithFeedback(100, .5),
                                                LinearSeparators(),
                                                PredictionNeurons()),
                               StepWithFeedback(SigmoidMaskedInputWithFeedback(100),
                                                LinearSeparators(),
                                                PredictionNeurons()),
                               StepWithFeedback(AllOnesMaskedInputWithFeedback(100),
                                                LinearSeparators(),
                                                PredictionNeurons()),
                               StepWithFeedback(RandomMaskedInputWithFeedback(100),
                                                LinearSeparators(),
                                                PredictionNeurons()),
                               StepWithFeedback(SoftmaxMaskedInputWithFeedback(100),
                                                LinearSeparators(),
                                                PredictionNeurons())],
                        weighted_addition=WeightedAdd(kernel_regularizer=tf.keras.regularizers.L2(l2=0.1))
                       ))


model.compile(loss=tf.losses.MeanSquaredError(),
              optimizer=tf.keras.optimizers.Adam(learning_rate=.05))

history = model.fit(X, y,
                    epochs=100,
                    verbose=1)

Epoch 1/100
313/313 [==============================] - 5s 5ms/step - loss: 1.4881
Epoch 2/100
313/313 [==============================] - 2s 5ms/step - loss: 0.3608
Epoch 3/100
313/313 [==============================] - 1s 4ms/step - loss: 0.2047
Epoch 4/100
313/313 [==============================] - 1s 5ms/step - loss: 0.1595
Epoch 5/100
313/313 [==============================] - 1s 4ms/step - loss: 0.1589
Epoch 6/100
313/313 [==============================] - 1s 4ms/step - loss: 0.1413
Epoch 7/100
313/313 [==============================] - 1s 4ms/step - loss: 0.1377
Epoch 8/100
313/313 [==============================] - 1s 4ms/step - loss: 0.1278
Epoch 9/100
313/313 [==============================] - 1s 4ms/step - loss: 0.1253
Epoch 10/100
313/313 [==============================] - 1s 4ms/step - loss: 0.1186
Epoch 11/100
313/313 [==============================] - 1s 4ms/step - loss: 0.1142
Epoch 12/100
313/313 [==============================] - 1s 4ms/step - loss: 0.1157
Epoch 13/100


In [26]:
model.compile(loss=tf.losses.MeanSquaredError(),
              optimizer=tf.keras.optimizers.Adam(learning_rate=.01))

history = model.fit(X, y,
                    epochs=100,
                    verbose=1)

Epoch 1/100
313/313 [==============================] - 4s 4ms/step - loss: 0.0466
Epoch 2/100
313/313 [==============================] - 1s 4ms/step - loss: 0.0465
Epoch 3/100
313/313 [==============================] - 1s 4ms/step - loss: 0.0473
Epoch 4/100
313/313 [==============================] - 1s 4ms/step - loss: 0.0462
Epoch 5/100
313/313 [==============================] - 1s 4ms/step - loss: 0.0463
Epoch 6/100
313/313 [==============================] - 1s 4ms/step - loss: 0.0458
Epoch 7/100
313/313 [==============================] - 1s 4ms/step - loss: 0.0469
Epoch 8/100
313/313 [==============================] - 1s 4ms/step - loss: 0.0456
Epoch 9/100
313/313 [==============================] - 1s 4ms/step - loss: 0.0459
Epoch 10/100
313/313 [==============================] - 1s 4ms/step - loss: 0.0458
Epoch 11/100
313/313 [==============================] - 1s 4ms/step - loss: 0.0468
Epoch 12/100
313/313 [==============================] - 1s 4ms/step - loss: 0.0457
Epoch 13/100


In [24]:
model.predict([[.1, .9, .1, .1], [.1, .1, .1, .1]])

1/1 [==============================] - 1s 502ms/step


array([4.0032053, 1.0556179], dtype=float32)

In [8]:
model.layers[0].weighted_addition.kernel

<tf.Variable 'loris_net_layer_1/weighted_add_1/kernel:0' shape=(10,) dtype=float32, numpy=
array([-0.01554427,  0.02662213,  0.00081429, -0.00033744, -0.00046539,
        0.00025597, -0.18156847,  0.00032535,  0.00076619,  0.00272344],
      dtype=float32)>

In [9]:
model.layers[0].steps[0].vectorial_space_separators.kernel

<tf.Variable 'loris_net_layer_1/step_no_feedback_1/linear_separators_4/kernel:0' shape=(10, 4) dtype=float32, numpy=
array([[-10.306679 , -10.935148 , -10.498442 , -10.205225 ],
       [-12.198647 , -12.96962  , -12.052882 , -11.799391 ],
       [ -7.227336 , -12.31886  ,  -7.455321 , -10.698708 ],
       [-12.041654 , -14.278202 , -14.05422  , -14.085447 ],
       [-16.606619 , -11.759833 ,  -1.1286962,  -7.5626955],
       [-13.370773 , -14.330955 , -13.533044 , -14.412642 ],
       [-11.219266 ,  -9.217952 , -10.503316 ,  -9.721881 ],
       [ -9.413974 , -12.691992 , -11.196913 , -11.4593525],
       [-12.849973 , -12.729217 , -14.286117 , -13.571646 ],
       [-14.163567 ,  -8.495464 , -11.941258 , -12.606322 ]],
      dtype=float32)>

In [10]:
model.layers[0].steps[0].vectorial_space_separators.bias

<tf.Variable 'loris_net_layer_1/step_no_feedback_1/linear_separators_4/bias:0' shape=(10,) dtype=float32, numpy=
array([-11.355231, -13.466333, -13.139659, -14.822046, -12.049393,
       -14.455282, -14.05586 , -13.239362, -14.67975 , -11.068076],
      dtype=float32)>

In [11]:
model.layers[0].steps[0].prediction_neurons.kernel

<tf.Variable 'loris_net_layer_1/step_no_feedback_1/prediction_neurons_4/kernel:0' shape=(10, 1) dtype=float32, numpy=
array([[-2.977331 ],
       [ 5.745986 ],
       [-5.436726 ],
       [-1.7825449],
       [ 2.008772 ],
       [-3.7082412],
       [-1.3978025],
       [-0.6718559],
       [-4.1090918],
       [-3.0476859]], dtype=float32)>

In [12]:
model.layers[0].steps[0].prediction_neurons.bias

<tf.Variable 'loris_net_layer_1/step_no_feedback_1/prediction_neurons_4/bias:0' shape=(10,) dtype=float32, numpy=
array([-0.39410233,  0.7100196 ,  0.02299778, -0.01018157, -0.0135984 ,
        0.00743816, -0.7151999 ,  0.01008856,  0.02234369,  0.08257507],
      dtype=float32)>

In [13]:
model.layers[0].weighted_addition.kernel

<tf.Variable 'loris_net_layer_1/weighted_add_1/kernel:0' shape=(10,) dtype=float32, numpy=
array([-0.01554427,  0.02662213,  0.00081429, -0.00033744, -0.00046539,
        0.00025597, -0.18156847,  0.00032535,  0.00076619,  0.00272344],
      dtype=float32)>

In [14]:
model.layers[0].weighted_addition.bias

<tf.Variable 'loris_net_layer_1/weighted_add_1/bias:0' shape=(1,) dtype=float32, numpy=array([2.9335077], dtype=float32)>

In [15]:
x = 0

(x*1.6993318+0.11208692)*1.8396976+0.7068256

0.9130316377153921