In [1]:
import tensorflow as tf
from LorisNet import *

In [2]:
X = tf.cast(tf.random.uniform((3, 2, 1)) <= .5,
            dtype=tf.float32)

X

<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[0.],
        [0.]],

       [[1.],
        [0.]],

       [[1.],
        [1.]]], dtype=float32)>

In [3]:
l = PredictionNeurons(units=1)

l(X)

<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[ 0.        ],
        [ 0.        ]],

       [[ 0.608824  ],
        [ 0.        ]],

       [[ 0.608824  ],
        [-0.13419974]]], dtype=float32)>

In [4]:
l.kernel

<tf.Variable 'prediction_neurons/kernel:0' shape=(2, 1, 1) dtype=float32, numpy=
array([[[ 0.608824  ]],

       [[-0.13419974]]], dtype=float32)>

In [5]:
l.bias

<tf.Variable 'prediction_neurons/bias:0' shape=(2, 1) dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>

In [6]:
X = tf.cast(tf.random.uniform((3, 2, 2)) <= .5,
            dtype=tf.float32)

X

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.]],

       [[1., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 0.]]], dtype=float32)>

In [7]:
l = PredictionNeurons(units=1)

l(X)

<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[ 0.        ],
        [ 0.        ]],

       [[-0.03124356],
        [-0.55174875]],

       [[ 0.3252859 ],
        [ 0.        ]]], dtype=float32)>

In [8]:
l.kernel

<tf.Variable 'prediction_neurons_1/kernel:0' shape=(2, 1, 2) dtype=float32, numpy=
array([[[-0.35652947,  0.3252859 ]],

       [[-0.67697   , -0.55174875]]], dtype=float32)>

In [9]:
l = PredictionNeurons(units=2)

l(X)

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[ 0.        ,  0.        ],
        [ 0.        ,  0.        ]],

       [[ 0.68908244,  0.7368564 ],
        [ 0.56760854, -0.6608713 ]],

       [[ 0.6192314 , -0.09320784],
        [ 0.        ,  0.        ]]], dtype=float32)>

In [10]:
l.kernel

<tf.Variable 'prediction_neurons_2/kernel:0' shape=(2, 2, 2) dtype=float32, numpy=
array([[[ 0.06985104,  0.6192314 ],
        [ 0.83006424, -0.09320784]],

       [[-0.02365828,  0.56760854],
        [-0.34869534, -0.6608713 ]]], dtype=float32)>