In [1]:
from LorisNet import *
import tensorflow as tf

In [2]:
X = tf.random.uniform((3, 2))

X

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.34617925, 0.23332465],
       [0.09996319, 0.43747115],
       [0.03560889, 0.43966746]], dtype=float32)>

In [3]:
s = StepNoFeedback(AllOnesMaskedInputNoFeedback(4),
                   LinearSeparators(),
                   PredictionNeurons(units=1)
                  )

s(X)

(<tf.Tensor: shape=(3, 4, 1), dtype=float32, numpy=
 array([[[0.3449342 ],
         [0.36041698],
         [0.19241135],
         [0.24615122]],
 
        [[0.3002882 ],
         [0.32640117],
         [0.20823395],
         [0.2610625 ]],
 
        [[0.29055822],
         [0.325723  ],
         [0.20868361],
         [0.26717603]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4, 1), dtype=float32, numpy=
 array([[[0.5702148 ],
         [0.45438036],
         [0.5435575 ],
         [0.4251093 ]],
 
        [[0.49641   ],
         [0.41149637],
         [0.588256  ],
         [0.45086145]],
 
        [[0.48032522],
         [0.4106414 ],
         [0.5895263 ],
         [0.46141967]]], dtype=float32)>)

In [4]:
s = StepNoFeedback(AllOnesMaskedInputNoFeedback(4),
                   LinearSeparators(),
                   PredictionNeurons(units=2)
                  )

s(X)

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[ 0.23330763,  0.20244361],
         [ 0.06034079,  0.05434024],
         [-0.22679655,  0.28828347],
         [ 0.18380556,  0.3457544 ]],
 
        [[ 0.22974886,  0.19935562],
         [ 0.06704023,  0.06037346],
         [-0.22833699,  0.2902415 ],
         [ 0.18257451,  0.34343868]],
 
        [[ 0.22837082,  0.19815987],
         [ 0.06804482,  0.06127814],
         [-0.2270857 ,  0.28865096],
         [ 0.1822201 ,  0.34277204]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4, 1), dtype=float32, numpy=
 array([[[0.5213535 ],
         [0.48482084],
         [0.5346841 ],
         [0.5056747 ]],
 
        [[0.513401  ],
         [0.5386489 ],
         [0.5383158 ],
         [0.5022879 ]],
 
        [[0.51032156],
         [0.54672045],
         [0.53536576],
         [0.5013129 ]]], dtyp

In [5]:
prior_masks = tf.random.uniform((4, 5, 2))  # nbr masks, nbr prior masks, input dim

prior_masks

<tf.Tensor: shape=(4, 5, 2), dtype=float32, numpy=
array([[[0.27896667, 0.42844093],
        [0.49938738, 0.04502499],
        [0.9670057 , 0.51873815],
        [0.08973134, 0.610579  ],
        [0.264629  , 0.93021214]],

       [[0.9391912 , 0.2569152 ],
        [0.36263943, 0.887625  ],
        [0.3378483 , 0.02049363],
        [0.73770666, 0.6122092 ],
        [0.13505149, 0.6978799 ]],

       [[0.17800236, 0.9410336 ],
        [0.47867942, 0.7204573 ],
        [0.510877  , 0.23137939],
        [0.12933922, 0.50926363],
        [0.83841753, 0.8222896 ]],

       [[0.2712698 , 0.94607794],
        [0.8613924 , 0.11968565],
        [0.56804264, 0.44026566],
        [0.45729518, 0.05606043],
        [0.5522417 , 0.8859829 ]]], dtype=float32)>

In [6]:
prior_spacial_indicators = tf.random.uniform((3, 4, 5))

prior_spacial_indicators

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0.30537403, 0.3868475 , 0.4828881 , 0.23279715, 0.7722249 ],
        [0.873196  , 0.11857331, 0.23658371, 0.12975132, 0.72630906],
        [0.16155231, 0.46725786, 0.08772993, 0.6007781 , 0.68788993],
        [0.98215246, 0.44868588, 0.00503707, 0.11808217, 0.70148265]],

       [[0.03085124, 0.8423419 , 0.16728842, 0.4664675 , 0.90744364],
        [0.92441773, 0.22681701, 0.50835705, 0.5582608 , 0.50137174],
        [0.6271589 , 0.22509658, 0.31789935, 0.555753  , 0.622916  ],
        [0.991838  , 0.9098451 , 0.9960681 , 0.9615649 , 0.03560948]],

       [[0.906662  , 0.4495194 , 0.09040964, 0.8877772 , 0.05352414],
        [0.26305032, 0.38315153, 0.5735986 , 0.24909139, 0.85126257],
        [0.49261177, 0.76107216, 0.70280945, 0.6941341 , 0.10145557],
        [0.03291106, 0.91461945, 0.5351708 , 0.05594039, 0.6490482 ]]],
      dtype=float32)>

In [7]:
s = StepWithFeedback(AllOnesMaskedInputWithFeedback(4),
                     LinearSeparators(),
                     PredictionNeurons(units=1)
                    )

s([X, prior_masks, prior_spacial_indicators])

(<tf.Tensor: shape=(3, 4, 1), dtype=float32, numpy=
 array([[[ 0.2073555 ],
         [ 0.09030516],
         [-0.00903746],
         [-0.6119548 ]],
 
        [[ 0.12916571],
         [ 0.18311608],
         [-0.2120857 ],
         [-0.7027017 ]],
 
        [[ 0.5431168 ],
         [-0.06822281],
         [ 0.09245186],
         [-0.5165236 ]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4, 1), dtype=float32, numpy=
 array([[[0.5065474 ],
         [0.4342641 ],
         [0.5479716 ],
         [0.6070154 ]],
 
        [[0.5866813 ],
         [0.41165733],
         [0.603297  ],
         [0.6108551 ]],
 
        [[0.59570277],
         [0.41519693],
         [0.60544765],
         [0.6011225 ]]], dtype=float32)>)

In [8]:
s = StepWithFeedback(AllOnesMaskedInputWithFeedback(4),
                     LinearSeparators(),
                     PredictionNeurons(units=2)
                    )

s([X, prior_masks, prior_spacial_indicators])

(<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
 array([[[-0.03080851, -0.01689063],
         [-0.27926773,  0.08529964],
         [ 0.32989383,  0.21101171],
         [-0.25624335,  0.33558553]],
 
        [[-0.01291794, -0.03963038],
         [-0.24399242, -0.10604595],
         [ 0.53481615, -0.1385482 ],
         [ 0.13127059,  0.3383639 ]],
 
        [[-0.25915316, -0.15770139],
         [-0.11195087, -0.15672411],
         [ 0.4426628 , -0.11184054],
         [ 0.4986598 ,  0.14746228]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4, 1), dtype=float32, numpy=
 array([[[0.3905609 ],
         [0.5936675 ],
         [0.40647614],
         [0.50989914]],
 
        [[0.38086277],
         [0.5516934 ],
         [0.44376975],
         [0.5899898 ]],
 
        [[0.3900316 ],
         [0.5372068 ],
         [0.45763752],
         [0.598679  ]]], dtyp